Complete homework 12 aka 'docker-1'
Otus-DevOps-2018-05/pavelvizir_microservices pull request #1
Opened 2018-07-24 12:10 UTC by pavelvizir

# Выполнено ДЗ №12

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Практика использования `docker`

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-08-02 18:21 UTC, Avtandilko requested changes
Павел, добавьте пожалуйста интеграцию с travis-ci (как в предыдущем репозитории).

2018-08-03 12:53 UTC, pavelvizir commented
Добавил интеграцию с travis-ci. 

Как мне теперь правильно прогнать тесты для остальных пулл-реквестов?

2018-08-03 15:19 UTC, Avtandilko approved these changes

2018-08-03 15:20 UTC, Avtandilko commented
Теперь отлично :) На вопрос про остальные ветки ответил в слаке.

2018-08-03 15:41 UTC, merged